swagger: '2.0'
info:
  title: IoT
  description: Data processing
  version: 1.0.0
host: iot-sensors-xwm423rbya-uc.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
    address: https://circular-light-265709.appspot.com
#  jwt_audience: 994414802550-t0rc8hisebaue4g785bi8mr6uekkcr46.apps.googleusercontent.com
paths:
  /publishMessage :
    get:
      summary: Get data
      operationId: get-sensors
      responses:
        '200':
          description: A successful response
          schema:
            type: string
    post:
      summary: Post data
      operationId: post-sensors
      responses:
        '200':
          description: A successful response
          schema:
            type: string